"use client";

import type { CSSProperties, ComponentType } from "react";
import {
  Search,
  TrendingUp,
  Zap,
  Gauge,
  Palette,
  Smartphone,
  Code2,
  MessagesSquare,
  PenTool,
  Rocket,
  Bot,
  Building2,
  LayoutDashboard,
  ShoppingCart,
  Wrench,
  CalendarDays,
  FolderCheck,
  Timer,
  Activity,
  Coffee,
  Ghost,
  MapPinned,
  Mail,
  MessageCircle,
  Instagram,
  Github,
  Linkedin,
  Music2,
  Circle,
  Globe,
  ShieldCheck,
  Layout,
  Briefcase,
  Clock,
  HeartHandshake,
  CalendarClock,
  LifeBuoy,
} from "lucide-react";
import {
  SiHtml5,
  SiCss,
  SiJavascript,
  SiTypescript,
  SiJquery,
  SiBootstrap,
  SiTailwindcss,
  SiWordpress,
  SiReact,
  SiNextdotjs,
  SiVuedotjs,
  SiNuxt,
  SiFlutter,
  SiNodedotjs,
  SiPhp,
  SiLaravel,
  SiMysql,
  SiPython,
  SiGit,
} from "react-icons/si";

type IconComponent = ComponentType<{ size?: number; style?: CSSProperties; className?: string; color?: string }>;

const REGISTRY: Record<string, IconComponent> = {
  Search,
  TrendingUp,
  Zap,
  Gauge,
  Palette,
  Smartphone,
  Code2,
  MessagesSquare,
  PenTool,
  Rocket,
  Bot,
  Building2,
  LayoutDashboard,
  ShoppingCart,
  Wrench,
  CalendarDays,
  FolderCheck,
  Timer,
  Activity,
  Coffee,
  Ghost,
  MapPinned,
  Mail,
  MessageCircle,
  Instagram,
  Github,
  Linkedin,
  Music2,
  Globe,
  ShieldCheck,
  Layout,
  Briefcase,
  Clock,
  HeartHandshake,
  CalendarClock,
  LifeBuoy,
  SiHtml5,
  SiCss,
  SiJavascript,
  SiTypescript,
  SiJquery,
  SiBootstrap,
  SiTailwindcss,
  SiWordpress,
  SiReact,
  SiNextdotjs,
  SiVuedotjs,
  SiNuxt,
  SiFlutter,
  SiNodedotjs,
  SiPhp,
  SiLaravel,
  SiMysql,
  SiPython,
  SiGit,
};

export function Icon({
  name,
  size = 16,
  style,
  className,
}: {
  name?: string | null;
  size?: number;
  style?: CSSProperties;
  className?: string;
}) {
  const Component = (name && REGISTRY[name]) || Circle;
  return <Component size={size} style={style} className={className} />;
}
